/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.PetDAO;
import Entidades.Pet;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Silva
 */
public class FormPet extends javax.swing.JFrame {

    /**
     * Creates new form Animal
     */
    public FormPet() throws SQLException {
        initComponents();
        exibirPet();// msotra a tabela dos pets
        idPet.setVisible(false);// esconde o label do id 
        btnAlterar.setVisible(false);// esconde o botão alterar
        btnExcluir.setVisible(false);// escond eo botão excluir
    }

    PetDAO petdao = new PetDAO();// instancia a classe petdao, delegando os metodos crud
    Pet pet = new Pet();// instancia a class epet, delegando os métodos getters e setters

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        lbPet = new javax.swing.JLabel();
        tbNome = new javax.swing.JTextField();
        tbRaca = new javax.swing.JTextField();
        lbNome = new javax.swing.JLabel();
        lbRaca = new javax.swing.JLabel();
        lbSexo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        cbxSexo = new javax.swing.JComboBox<>();
        cbxTipoAnimal = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPet = new javax.swing.JTable();
        btnAlterar = new javax.swing.JButton();
        idPet = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lbPet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbPet.setText("Pet");

        lbNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbNome.setText("Nome:");

        lbRaca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbRaca.setText("Raça:");

        lbSexo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbSexo.setText("Sexo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Tipo de animal:");

        btnCadastrar.setBackground(new java.awt.Color(0, 153, 153));
        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(0, 153, 153));
        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        cbxTipoAnimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gato", "Cachorro" }));

        tblPet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Nome", "Tipo Animal", "Sexo", "Raça"
            }
        ));
        tblPet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPet);

        btnAlterar.setBackground(new java.awt.Color(0, 153, 153));
        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        idPet.setText("id");

        btnVoltar.setBackground(new java.awt.Color(0, 153, 153));
        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar a tela Inicial");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/img/vet.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(lbPet, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbNome)
                                        .addComponent(lbRaca)
                                        .addComponent(lbSexo))
                                    .addGap(30, 30, 30)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(61, 61, 61)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cbxTipoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(tbRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(idPet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(lbPet, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNome))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbRaca))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSexo)
                            .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cbxTipoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addComponent(idPet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // Ação do botão de excluir:

        //Questiona ao usuário se deseja realmente excluir o cadastro
        int conf = JOptionPane.showConfirmDialog(null, "Deseja Realmente excluir o cadastro?", "Atenção", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        if (conf == 0) {
            //caso positivo
            pet.setIdPet(Integer.parseInt(idPet.getText()));// seta o id do pet na label
            try {
                petdao.excluir(pet);// metodo de excluir delegado da classe dao, que tem como argumento a classe pet
                JOptionPane.showMessageDialog(null, "Operação realizada com sucesso");
                limparCampos();// limpa os campos
                exibirPet();// atualiza a tabela
                btnAlterar.setVisible(false);// esconde o botão alterar
                btnExcluir.setVisible(false);// esconde o botão exluir
                btnCadastrar.setVisible(true);// mostra o botão cadastrar
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "O procedimento de exclusão foi cancelado!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // Ação do botão cadastrar:
        try {
            //Aqui verifica se algum campo está em branco e se estiver mostra uma mensagem solicitando o preenchimento e foca o cursor no respectivo campo
            if (tbNome.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Favor, digite o nome do Animal");
                tbNome.grabFocus();
            } else if (tbRaca.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Favor, digite a raça do Animal");
                tbRaca.grabFocus();
            } else {
                //Seta os dados preenchidos nos campos de texto e comboboxes
                pet.setNome(tbNome.getText());
                pet.setRaca(tbRaca.getText());
                pet.setSexo((String) cbxSexo.getSelectedItem());
                pet.setTipoAnimal((String) cbxTipoAnimal.getSelectedItem());
                petdao.cadastrar(pet);// metodo de cadastrar , delegado da classe dao que tem como argumento a classe pet
                JOptionPane.showMessageDialog(null, "Animal " + pet.getNome() + " cadastrado com sucesso!");
                exibirPet();// atualiz a atabela
                limparCampos();// limpa os campos
                //Aqui o programa mostra uma caixa de diálogo se ele deseja fazer o agendamento
                int opcao = JOptionPane.showConfirmDialog(null, "Deseja realizar o agendamento?", "Atenção", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
                switch (opcao) {
                    case 0:
                        //caso positivo
                        FormAgendamento agenda = new FormAgendamento();// Instancia o formulario do agendamento
                        this.setVisible(false);// fecha a tela atual
                        agenda.setVisible(true);// abre a tela do agendamento
                        break;
                    case 1:
                        // caso negativo, não acontece nada
                        break;
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu o seguinte erro: " + e.getLocalizedMessage());
        }


    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // Ação do botão de alterar:

        //Pega os dados dos campos que foram alterados
        pet.setNome(tbNome.getText());
        pet.setTipoAnimal((String) cbxTipoAnimal.getSelectedItem());
        pet.setRaca((tbRaca.getText()));
        pet.setSexo((String) cbxSexo.getSelectedItem());
        pet.setIdPet(Integer.parseInt(idPet.getText()));
        try {
            petdao.alterar(pet);// metodo de alterar, delagado da classe dao, que recebe como argumento a classe pet
            JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso");
            limparCampos();// limpa os campos
            exibirPet();// atualiz a atabela
            btnAlterar.setVisible(false);// esconde o botão de alterar
            btnExcluir.setVisible(false);// esconde o botão de excluir
            btnCadastrar.setVisible(true);// mostra o botão de cadastrar
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void tblPetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPetMouseClicked
        // // Ação de clicar em um dos itens da tabela:
        exibirPetFiltro();// seta os dados selecionados da tabela nos campos de texto e comboboxes
        btnCadastrar.setVisible(false);// esconde o botão de cadastrar
        btnAlterar.setVisible(true);// exibe o botão de alterar
        btnExcluir.setVisible(true);// exibe o botão de excluir

    }//GEN-LAST:event_tblPetMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // Ação do clique em um local em branco do formulário:
        limparCampos();// limpa os campos de texto
        btnAlterar.setVisible(false);// esconde o botão alterar
        btnExcluir.setVisible(false);// esconde o botão excluir
        btnCadastrar.setVisible(true);// mostra o botão de cadastrar
    }//GEN-LAST:event_formMouseClicked

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // Ação do botão de voltar a tela inicial:
        TelaInicial inicio = new TelaInicial();// Instancia a classe tela inicial
        this.setVisible(false);// fecha a tela atual
        inicio.setVisible(true);// Mosra a tela inicial
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormPet().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FormPet.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private void exibirPet() throws SQLException {
        // Declara uma nova defaulttablemodel, que é atribuida ao modelo da tabela criada na interface gráfica
        DefaultTableModel tabelapets = (DefaultTableModel) tblPet.getModel();

        tabelapets.setRowCount(0);//Seta as linhas em 0

        for (Iterator<Object> it = petdao.exibir().iterator(); it.hasNext();) {
            //Iterador, que tem como argumentos o metodo exibir pet, e adiciona dados a cada linha constante na tabela agenda
            Entidades.Pet pets = (Entidades.Pet) it.next();//Cast de Pet no iterador
            tabelapets.addRow(new Object[]{
                pets.getIdPet(),
                pets.getNome(),
                pets.getRaca(),
                pets.getSexo(),
                pets.getTipoAnimal()
            });

        }
    }

    private void limparCampos() {
        // limpa os campos de texto
        tbNome.setText("");
        tbRaca.setText("");

    }

    private void exibirPetFiltro() {
        //Seta os itens nos campos de texto e comboboxes de acordo com o item selecionado da tabela
        tbNome.setText(tblPet.getValueAt(tblPet.getSelectedRow(), 1).toString());
        tbRaca.setText(tblPet.getValueAt(tblPet.getSelectedRow(), 2).toString());
        cbxSexo.setSelectedItem(tblPet.getValueAt(tblPet.getSelectedRow(), 3).toString());
        cbxTipoAnimal.setSelectedItem(tblPet.getValueAt(tblPet.getSelectedRow(), 4).toString());
        idPet.setText(tblPet.getValueAt(tblPet.getSelectedRow(), 0).toString());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JComboBox<String> cbxTipoAnimal;
    private javax.swing.JLabel idPet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbPet;
    private javax.swing.JLabel lbRaca;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JTextField tbNome;
    private javax.swing.JTextField tbRaca;
    private javax.swing.JTable tblPet;
    // End of variables declaration//GEN-END:variables
}
