/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.ResponsavelDAO;
import Entidades.Responsavel;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Silva
 */
public class FormResponsavel extends javax.swing.JFrame {

    /**
     * Creates new form Responsavel
     */
    public FormResponsavel() throws SQLException {
        initComponents();
        exibirResp();// Mostra a tabela dos responsaveis
        btnAlterar.setVisible(false);// Esconde o botão de alterar
        btnExcluir.setVisible(false);// Esconde o botão de Excluir
        idResp.setVisible(false);// Esconde o label do id
    }
    Responsavel resp = new Responsavel();// Instancia a classe responsavel, delegando os métodos getters e setters
    ResponsavelDAO respdao = new ResponsavelDAO();// Instancia a classe dao, delegando os métodos do crud

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTelCelular = new javax.swing.JLabel();
        lbSexo = new javax.swing.JLabel();
        tbNome = new javax.swing.JTextField();
        cbxSexo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lbCPF = new javax.swing.JLabel();
        tbEmail = new javax.swing.JTextField();
        lbNome = new javax.swing.JLabel();
        lbRG = new javax.swing.JLabel();
        tbCPF = new javax.swing.JTextField();
        lbTelFixo = new javax.swing.JLabel();
        tbTelFixo = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        tbRG = new javax.swing.JTextField();
        tbTelCelular = new javax.swing.JTextField();
        idResp = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResponsavel = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lbTelCelular.setText("Telefone Celular:");

        lbSexo.setText("Sexo");

        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jLabel1.setText("Responsável");

        lbCPF.setText("CPF:");

        lbNome.setText("Nome:");

        lbRG.setText("RG:");

        lbTelFixo.setText("Telefone Fixo:");

        lbEmail.setText("Email:");

        idResp.setText("id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbRG)
                                    .addComponent(lbCPF)
                                    .addComponent(lbNome)
                                    .addComponent(lbSexo))
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbTelFixo)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tbNome)
                                .addComponent(tbRG)
                                .addComponent(tbCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tbTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idResp)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbEmail)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbTelCelular)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tbTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRG))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSexo))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelFixo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelCelular)
                    .addComponent(tbTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail))
                .addGap(34, 34, 34)
                .addComponent(idResp)
                .addGap(37, 37, 37))
        );

        btnCadastrar.setBackground(new java.awt.Color(0, 153, 153));
        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(0, 153, 153));
        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(0, 153, 153));
        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tblResponsavel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nome", "CPF", "RG", "Sexo", "Telefone Fixo", "Telefone Celular", "E-mail"
            }
        ));
        tblResponsavel.getTableHeader().setReorderingAllowed(false);
        tblResponsavel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResponsavelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblResponsavel);

        btnVoltar.setBackground(new java.awt.Color(0, 153, 153));
        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar a tela Inicial");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/img/vet.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btnCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCadastrar)
                            .addComponent(btnAlterar)
                            .addComponent(btnExcluir))
                        .addGap(4, 4, 4)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // Ação do botão de alterar:
        
        //Pega os dados dos campos que foram alterados
        resp.setNome(tbNome.getText());
        resp.setCpf(Long.parseLong(tbCPF.getText()));
        resp.setRg(Integer.parseInt(tbRG.getText()));
        resp.setSexo((String) cbxSexo.getSelectedItem());
        resp.setTelFixo(Long.parseLong(tbTelFixo.getText()));
        resp.setTelCelular(Long.parseLong(tbTelCelular.getText()));
        resp.setEmail(tbEmail.getText());
        resp.setIdResponsavel(Integer.parseInt(idResp.getText()));
        try {
            //executa o método de alterar, delegado da classe dao
            respdao.alterar(resp);
            JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso");
            limparCampos();// limpa os campos
            exibirResp();// atualiza a tabela
            btnAlterar.setVisible(false);// esconde o botão de alterar
            btnExcluir.setVisible(false);// esconde o botão de excluir
            btnCadastrar.setVisible(true);// mostra o botão de cadastrar
        } catch (Exception e) {
            e.printStackTrace();
        }
        

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // Ação do botão de cadastrar:

        try {
            //Aqui verifica se algum campo está em branco e se estiver mostra uma mensagem solicitando o preenchimento e foca o cursor no respectivo campo
            if (tbNome.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Favor, digite o nome do Responsável");
                tbNome.grabFocus();
            } else if (tbCPF.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Favor, digite o CPF do responsável");
                tbCPF.grabFocus();
            } else if (tbRG.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Favor, digite o RG do responsável");
                tbRG.grabFocus();
            } else if (tbTelFixo.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Favor, digite o telefone fixo do responsável");
                tbTelFixo.grabFocus();
            } else if (tbTelCelular.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Favor, digite o telefone celular do responsável");
                tbTelCelular.grabFocus();
            } else if (tbEmail.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Favor, digite o email do responsável");
                tbEmail.grabFocus();
            } else {
                //Seta os dados preenchidos nos campos de texto e comboboxes
                resp.setNome(tbNome.getText());
                resp.setCpf(Long.parseLong(tbCPF.getText()));
                resp.setRg(Integer.parseInt(tbRG.getText()));
                resp.setSexo((String) cbxSexo.getSelectedItem());
                resp.setTelFixo(Long.parseLong(tbTelFixo.getText()));
                resp.setTelCelular(Long.parseLong(tbTelCelular.getText()));
                resp.setEmail(tbEmail.getText());
                respdao.cadastrar(resp);// método de cadatsrar delagado da classe dao, cujo argumento a classe responsavel
                JOptionPane.showMessageDialog(null, "Responsável " + resp.getNome() + " cadastrado com sucesso!");
                limparCampos();// limpar os campos preenchidos
                exibirResp();// Atualiza a tabela
                //Aqui o programa mostra uma caixa de diálogo se ele deseja cadastrar um novo pet
                int opcao = JOptionPane.showConfirmDialog(null, "Deseja cadastrar um animal?", "Atenção", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
                switch (opcao) {
                    case 0:
                        //caso positivo
                        FormPet pet = new FormPet();// Instancia o formulario do pet
                        this.setVisible(false);// fecha a tela atual
                        pet.setVisible(true);// Abre a tela dos pets
                        break;
                    case 1:
                        //Caso negativo, não ocorre nada
                        break;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu o seguinte erro: " + e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
          // Ação do botão de excluir:

        //Questiona ao usuário se deseja realmente excluir o cadastro
        int conf = JOptionPane.showConfirmDialog(null, "Deseja Realmente excluir o cadastro?", "Atenção", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        if (conf == 0) {
            // caso positivo
            resp.setIdResponsavel(Integer.parseInt(idResp.getText()));//seta o id do responsavel na lab id, que está escondida
            try {
                respdao.excluir(resp);// método de exluir, dlegado da classe dao, que tem como argumento a classe responsavel
                JOptionPane.showMessageDialog(null, "Operação realizada com sucesso");
                limparCampos();// limpa os campos
                exibirResp();// atualiza a tabela
                btnAlterar.setVisible(false);// esconde o botão alterar
                btnExcluir.setVisible(false);// esconde o botão excluir
                btnCadastrar.setVisible(true);// mosstra o botão cadastrar
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            // caso negativo
            JOptionPane.showMessageDialog(null, "O procedimento de exclusão foi cancelado!");
        }
        

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tblResponsavelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResponsavelMouseClicked
        // Ação de clicar em um dos itens da tabela:
        exibirResponsavelFiltro();// seta os dados selecionados da tabela nos campos de texto e comboboxes
        btnCadastrar.setVisible(false);// esconde o botão de cadastrar
        btnAlterar.setVisible(true);// exibe o botão de alterar
        btnExcluir.setVisible(true);// exibe o botão de excluir
    }//GEN-LAST:event_tblResponsavelMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // Ação do clique nos espaços em branco do formulário:
        limparCampos();// limpa os campos preenchidos
        btnAlterar.setVisible(false);// esconde o botão alterar
        btnExcluir.setVisible(false);// esconde o botão excluir
        btnCadastrar.setVisible(true);// mostra o botão cadastrar
    }//GEN-LAST:event_formMouseClicked

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
       // Ação do botão de voltar a tela inicial:
        TelaInicial inicio = new TelaInicial();// Instancia a classe tela inicial
        this.setVisible(false);// fecha a tela atual
        inicio.setVisible(true);// Mosra a tela inicial
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormResponsavel().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FormResponsavel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    private void exibirResp() throws SQLException {
         // Declara uma nova defaulttablemodel, que é atribuida ao modelo da tabela criada na interface gráfica
        DefaultTableModel tabelaResp = (DefaultTableModel) tblResponsavel.getModel();
        
        tabelaResp.setRowCount(0);//Seta as linhas em 0
        
        for (Iterator<Object> it = respdao.exibir().iterator(); it.hasNext();) {
            //Iterador, que tem como argumentos o metodo exibir funcionario, e adiciona dados a cada linha constante na tabela agenda
            Entidades.Responsavel resp = (Entidades.Responsavel) it.next();//Cast de Funcionario no iterador
            tabelaResp.addRow(new Object[]{
                resp.getIdResponsavel(),
                resp.getNome(),
                resp.getCpf(),
                resp.getRg(),
                resp.getSexo(),
                resp.getTelFixo(),
                resp.getTelCelular(),
                resp.getEmail()
            });
            
        }
    }
    
    private void exibirResponsavelFiltro() {
        //Seta os itens nos campos de texto e comboboxes de acordo com o item selecionado da tabela
        tbNome.setText(tblResponsavel.getValueAt(tblResponsavel.getSelectedRow(), 1).toString());
        tbCPF.setText(tblResponsavel.getValueAt(tblResponsavel.getSelectedRow(), 2).toString());
        tbRG.setText(tblResponsavel.getValueAt(tblResponsavel.getSelectedRow(), 3).toString());
        cbxSexo.setSelectedItem(tblResponsavel.getValueAt(tblResponsavel.getSelectedRow(), 4).toString());
        tbTelFixo.setText(tblResponsavel.getValueAt(tblResponsavel.getSelectedRow(), 5).toString());
        tbTelCelular.setText(tblResponsavel.getValueAt(tblResponsavel.getSelectedRow(), 6).toString());
        tbEmail.setText(tblResponsavel.getValueAt(tblResponsavel.getSelectedRow(), 7).toString());
        idResp.setText(tblResponsavel.getValueAt(tblResponsavel.getSelectedRow(), 0).toString());
    }
    
    private void limparCampos() {
        // Limpa os campos
        tbNome.setText("");
        tbCPF.setText("");
        tbRG.setText("");
        tbTelFixo.setText("");
        tbTelCelular.setText("");
        tbEmail.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JLabel idResp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbRG;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JLabel lbTelCelular;
    private javax.swing.JLabel lbTelFixo;
    private javax.swing.JTextField tbCPF;
    private javax.swing.JTextField tbEmail;
    private javax.swing.JTextField tbNome;
    private javax.swing.JTextField tbRG;
    private javax.swing.JTextField tbTelCelular;
    private javax.swing.JTextField tbTelFixo;
    private javax.swing.JTable tblResponsavel;
    // End of variables declaration//GEN-END:variables
}
